package com.xiaofengzi.xfzzone.db.domain;

import java.util.Date;

public class DicCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.CODE_TYPE
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.CODE_LABEL
     *
     * @mbggenerated
     */
    private String codeLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.REMARKS
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.SHOW_ORDER
     *
     * @mbggenerated
     */
    private Integer showOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.PARENT_CODE
     *
     * @mbggenerated
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.IS_DELETE
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.CREATED_DATE
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.MODIFIED_DATE
     *
     * @mbggenerated
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.CREATED_USER
     *
     * @mbggenerated
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.MODIFIED_USER
     *
     * @mbggenerated
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.STAND_BY_FLAG1
     *
     * @mbggenerated
     */
    private String standByFlag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.STAND_BY_FLAG2
     *
     * @mbggenerated
     */
    private String standByFlag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.STAND_BY_FLAG3
     *
     * @mbggenerated
     */
    private String standByFlag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.STAND_BY_FLAG4
     *
     * @mbggenerated
     */
    private String standByFlag4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_code.STAND_BY_FLAG5
     *
     * @mbggenerated
     */
    private String standByFlag5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.id
     *
     * @return the value of dic_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.id
     *
     * @param id the value for dic_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.CODE_TYPE
     *
     * @return the value of dic_code.CODE_TYPE
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.CODE_TYPE
     *
     * @param codeType the value for dic_code.CODE_TYPE
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.CODE
     *
     * @return the value of dic_code.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.CODE
     *
     * @param code the value for dic_code.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.CODE_LABEL
     *
     * @return the value of dic_code.CODE_LABEL
     *
     * @mbggenerated
     */
    public String getCodeLabel() {
        return codeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.CODE_LABEL
     *
     * @param codeLabel the value for dic_code.CODE_LABEL
     *
     * @mbggenerated
     */
    public void setCodeLabel(String codeLabel) {
        this.codeLabel = codeLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.REMARKS
     *
     * @return the value of dic_code.REMARKS
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.REMARKS
     *
     * @param remarks the value for dic_code.REMARKS
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.SHOW_ORDER
     *
     * @return the value of dic_code.SHOW_ORDER
     *
     * @mbggenerated
     */
    public Integer getShowOrder() {
        return showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.SHOW_ORDER
     *
     * @param showOrder the value for dic_code.SHOW_ORDER
     *
     * @mbggenerated
     */
    public void setShowOrder(Integer showOrder) {
        this.showOrder = showOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.PARENT_CODE
     *
     * @return the value of dic_code.PARENT_CODE
     *
     * @mbggenerated
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.PARENT_CODE
     *
     * @param parentCode the value for dic_code.PARENT_CODE
     *
     * @mbggenerated
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.IS_DELETE
     *
     * @return the value of dic_code.IS_DELETE
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.IS_DELETE
     *
     * @param isDelete the value for dic_code.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.CREATED_DATE
     *
     * @return the value of dic_code.CREATED_DATE
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.CREATED_DATE
     *
     * @param createdDate the value for dic_code.CREATED_DATE
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.MODIFIED_DATE
     *
     * @return the value of dic_code.MODIFIED_DATE
     *
     * @mbggenerated
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.MODIFIED_DATE
     *
     * @param modifiedDate the value for dic_code.MODIFIED_DATE
     *
     * @mbggenerated
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.CREATED_USER
     *
     * @return the value of dic_code.CREATED_USER
     *
     * @mbggenerated
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.CREATED_USER
     *
     * @param createdUser the value for dic_code.CREATED_USER
     *
     * @mbggenerated
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.MODIFIED_USER
     *
     * @return the value of dic_code.MODIFIED_USER
     *
     * @mbggenerated
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.MODIFIED_USER
     *
     * @param modifiedUser the value for dic_code.MODIFIED_USER
     *
     * @mbggenerated
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.STAND_BY_FLAG1
     *
     * @return the value of dic_code.STAND_BY_FLAG1
     *
     * @mbggenerated
     */
    public String getStandByFlag1() {
        return standByFlag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.STAND_BY_FLAG1
     *
     * @param standByFlag1 the value for dic_code.STAND_BY_FLAG1
     *
     * @mbggenerated
     */
    public void setStandByFlag1(String standByFlag1) {
        this.standByFlag1 = standByFlag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.STAND_BY_FLAG2
     *
     * @return the value of dic_code.STAND_BY_FLAG2
     *
     * @mbggenerated
     */
    public String getStandByFlag2() {
        return standByFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.STAND_BY_FLAG2
     *
     * @param standByFlag2 the value for dic_code.STAND_BY_FLAG2
     *
     * @mbggenerated
     */
    public void setStandByFlag2(String standByFlag2) {
        this.standByFlag2 = standByFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.STAND_BY_FLAG3
     *
     * @return the value of dic_code.STAND_BY_FLAG3
     *
     * @mbggenerated
     */
    public String getStandByFlag3() {
        return standByFlag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.STAND_BY_FLAG3
     *
     * @param standByFlag3 the value for dic_code.STAND_BY_FLAG3
     *
     * @mbggenerated
     */
    public void setStandByFlag3(String standByFlag3) {
        this.standByFlag3 = standByFlag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.STAND_BY_FLAG4
     *
     * @return the value of dic_code.STAND_BY_FLAG4
     *
     * @mbggenerated
     */
    public String getStandByFlag4() {
        return standByFlag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.STAND_BY_FLAG4
     *
     * @param standByFlag4 the value for dic_code.STAND_BY_FLAG4
     *
     * @mbggenerated
     */
    public void setStandByFlag4(String standByFlag4) {
        this.standByFlag4 = standByFlag4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_code.STAND_BY_FLAG5
     *
     * @return the value of dic_code.STAND_BY_FLAG5
     *
     * @mbggenerated
     */
    public String getStandByFlag5() {
        return standByFlag5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_code.STAND_BY_FLAG5
     *
     * @param standByFlag5 the value for dic_code.STAND_BY_FLAG5
     *
     * @mbggenerated
     */
    public void setStandByFlag5(String standByFlag5) {
        this.standByFlag5 = standByFlag5;
    }
}