package com.xiaofengzi.xfzzone.db.domain;

import java.util.Date;

public class OssObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.sn
     *
     * @mbggenerated
     */
    private String sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.save_type
     *
     * @mbggenerated
     */
    private String saveType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.acl
     *
     * @mbggenerated
     */
    private String acl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oss_object.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.id
     *
     * @return the value of oss_object.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.id
     *
     * @param id the value for oss_object.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.sn
     *
     * @return the value of oss_object.sn
     *
     * @mbggenerated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.sn
     *
     * @param sn the value for oss_object.sn
     *
     * @mbggenerated
     */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.path
     *
     * @return the value of oss_object.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.path
     *
     * @param path the value for oss_object.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.name
     *
     * @return the value of oss_object.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.name
     *
     * @param name the value for oss_object.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.size
     *
     * @return the value of oss_object.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.size
     *
     * @param size the value for oss_object.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.save_type
     *
     * @return the value of oss_object.save_type
     *
     * @mbggenerated
     */
    public String getSaveType() {
        return saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.save_type
     *
     * @param saveType the value for oss_object.save_type
     *
     * @mbggenerated
     */
    public void setSaveType(String saveType) {
        this.saveType = saveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.type
     *
     * @return the value of oss_object.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.type
     *
     * @param type the value for oss_object.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.url
     *
     * @return the value of oss_object.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.url
     *
     * @param url the value for oss_object.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.acl
     *
     * @return the value of oss_object.acl
     *
     * @mbggenerated
     */
    public String getAcl() {
        return acl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.acl
     *
     * @param acl the value for oss_object.acl
     *
     * @mbggenerated
     */
    public void setAcl(String acl) {
        this.acl = acl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.add_time
     *
     * @return the value of oss_object.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.add_time
     *
     * @param addTime the value for oss_object.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oss_object.num
     *
     * @return the value of oss_object.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oss_object.num
     *
     * @param num the value for oss_object.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }
}