package com.xiaofengzi.xfzzone.db.domain;

import java.util.Date;

public class UserPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.oss_id
     *
     * @mbggenerated
     */
    private String ossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.modified_time
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.id
     *
     * @return the value of user_photo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.id
     *
     * @param id the value for user_photo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.type
     *
     * @return the value of user_photo.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.type
     *
     * @param type the value for user_photo.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.oss_id
     *
     * @return the value of user_photo.oss_id
     *
     * @mbggenerated
     */
    public String getOssId() {
        return ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.oss_id
     *
     * @param ossId the value for user_photo.oss_id
     *
     * @mbggenerated
     */
    public void setOssId(String ossId) {
        this.ossId = ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.add_time
     *
     * @return the value of user_photo.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.add_time
     *
     * @param addTime the value for user_photo.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.modified_time
     *
     * @return the value of user_photo.modified_time
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.modified_time
     *
     * @param modifiedTime the value for user_photo.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.is_delete
     *
     * @return the value of user_photo.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.is_delete
     *
     * @param isDelete the value for user_photo.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}