package com.xiaofengzi.xfzzone.db.domain;

import java.util.Date;

public class UserPhotoAlbum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.account_num
     *
     * @mbggenerated
     */
    private String accountNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.oss_id
     *
     * @mbggenerated
     */
    private String ossId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.modified_time
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.id
     *
     * @return the value of user_photo_album.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.id
     *
     * @param id the value for user_photo_album.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.account_num
     *
     * @return the value of user_photo_album.account_num
     *
     * @mbggenerated
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.account_num
     *
     * @param accountNum the value for user_photo_album.account_num
     *
     * @mbggenerated
     */
    public void setAccountNum(String accountNum) {
        this.accountNum = accountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.name
     *
     * @return the value of user_photo_album.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.name
     *
     * @param name the value for user_photo_album.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.oss_id
     *
     * @return the value of user_photo_album.oss_id
     *
     * @mbggenerated
     */
    public String getOssId() {
        return ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.oss_id
     *
     * @param ossId the value for user_photo_album.oss_id
     *
     * @mbggenerated
     */
    public void setOssId(String ossId) {
        this.ossId = ossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.is_delete
     *
     * @return the value of user_photo_album.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.is_delete
     *
     * @param isDelete the value for user_photo_album.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.add_time
     *
     * @return the value of user_photo_album.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.add_time
     *
     * @param addTime the value for user_photo_album.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.modified_time
     *
     * @return the value of user_photo_album.modified_time
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.modified_time
     *
     * @param modifiedTime the value for user_photo_album.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}