package com.xiaofengzi.wxapi.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class DicCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public DicCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNull() {
            addCriterion("CODE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIsNotNull() {
            addCriterion("CODE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeTypeEqualTo(String value) {
            addCriterion("CODE_TYPE =", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotEqualTo(String value) {
            addCriterion("CODE_TYPE <>", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThan(String value) {
            addCriterion("CODE_TYPE >", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_TYPE >=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThan(String value) {
            addCriterion("CODE_TYPE <", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLessThanOrEqualTo(String value) {
            addCriterion("CODE_TYPE <=", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeLike(String value) {
            addCriterion("CODE_TYPE like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotLike(String value) {
            addCriterion("CODE_TYPE not like", value, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeIn(List<String> values) {
            addCriterion("CODE_TYPE in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotIn(List<String> values) {
            addCriterion("CODE_TYPE not in", values, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeBetween(String value1, String value2) {
            addCriterion("CODE_TYPE between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeTypeNotBetween(String value1, String value2) {
            addCriterion("CODE_TYPE not between", value1, value2, "codeType");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("CODE in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("CODE not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLabelIsNull() {
            addCriterion("CODE_LABEL is null");
            return (Criteria) this;
        }

        public Criteria andCodeLabelIsNotNull() {
            addCriterion("CODE_LABEL is not null");
            return (Criteria) this;
        }

        public Criteria andCodeLabelEqualTo(String value) {
            addCriterion("CODE_LABEL =", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelNotEqualTo(String value) {
            addCriterion("CODE_LABEL <>", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelGreaterThan(String value) {
            addCriterion("CODE_LABEL >", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_LABEL >=", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelLessThan(String value) {
            addCriterion("CODE_LABEL <", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelLessThanOrEqualTo(String value) {
            addCriterion("CODE_LABEL <=", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelLike(String value) {
            addCriterion("CODE_LABEL like", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelNotLike(String value) {
            addCriterion("CODE_LABEL not like", value, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelIn(List<String> values) {
            addCriterion("CODE_LABEL in", values, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelNotIn(List<String> values) {
            addCriterion("CODE_LABEL not in", values, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelBetween(String value1, String value2) {
            addCriterion("CODE_LABEL between", value1, value2, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andCodeLabelNotBetween(String value1, String value2) {
            addCriterion("CODE_LABEL not between", value1, value2, "codeLabel");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("REMARKS =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("REMARKS <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("REMARKS >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("REMARKS >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("REMARKS <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("REMARKS <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("REMARKS like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("REMARKS not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("REMARKS in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("REMARKS not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("REMARKS between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("REMARKS not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andShowOrderIsNull() {
            addCriterion("SHOW_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andShowOrderIsNotNull() {
            addCriterion("SHOW_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andShowOrderEqualTo(Integer value) {
            addCriterion("SHOW_ORDER =", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderNotEqualTo(Integer value) {
            addCriterion("SHOW_ORDER <>", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderGreaterThan(Integer value) {
            addCriterion("SHOW_ORDER >", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("SHOW_ORDER >=", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderLessThan(Integer value) {
            addCriterion("SHOW_ORDER <", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderLessThanOrEqualTo(Integer value) {
            addCriterion("SHOW_ORDER <=", value, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderIn(List<Integer> values) {
            addCriterion("SHOW_ORDER in", values, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderNotIn(List<Integer> values) {
            addCriterion("SHOW_ORDER not in", values, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderBetween(Integer value1, Integer value2) {
            addCriterion("SHOW_ORDER between", value1, value2, "showOrder");
            return (Criteria) this;
        }

        public Criteria andShowOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("SHOW_ORDER not between", value1, value2, "showOrder");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNull() {
            addCriterion("PARENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andParentCodeIsNotNull() {
            addCriterion("PARENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andParentCodeEqualTo(String value) {
            addCriterion("PARENT_CODE =", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotEqualTo(String value) {
            addCriterion("PARENT_CODE <>", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThan(String value) {
            addCriterion("PARENT_CODE >", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_CODE >=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThan(String value) {
            addCriterion("PARENT_CODE <", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLessThanOrEqualTo(String value) {
            addCriterion("PARENT_CODE <=", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeLike(String value) {
            addCriterion("PARENT_CODE like", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotLike(String value) {
            addCriterion("PARENT_CODE not like", value, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeIn(List<String> values) {
            addCriterion("PARENT_CODE in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotIn(List<String> values) {
            addCriterion("PARENT_CODE not in", values, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeBetween(String value1, String value2) {
            addCriterion("PARENT_CODE between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andParentCodeNotBetween(String value1, String value2) {
            addCriterion("PARENT_CODE not between", value1, value2, "parentCode");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("CREATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("CREATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(LocalDateTime value) {
            addCriterion("CREATED_DATE >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(LocalDateTime value) {
            addCriterion("CREATED_DATE <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("CREATED_DATE <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<LocalDateTime> values) {
            addCriterion("CREATED_DATE in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<LocalDateTime> values) {
            addCriterion("CREATED_DATE not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATED_DATE between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("CREATED_DATE not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("MODIFIED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("MODIFIED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(LocalDateTime value) {
            addCriterion("MODIFIED_DATE =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(LocalDateTime value) {
            addCriterion("MODIFIED_DATE <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(LocalDateTime value) {
            addCriterion("MODIFIED_DATE >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("MODIFIED_DATE >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(LocalDateTime value) {
            addCriterion("MODIFIED_DATE <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("MODIFIED_DATE <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<LocalDateTime> values) {
            addCriterion("MODIFIED_DATE in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<LocalDateTime> values) {
            addCriterion("MODIFIED_DATE not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("MODIFIED_DATE between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("MODIFIED_DATE not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("CREATED_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("CREATED_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("CREATED_USER =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("CREATED_USER <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("CREATED_USER >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_USER >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("CREATED_USER <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("CREATED_USER <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("CREATED_USER like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("CREATED_USER not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("CREATED_USER in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("CREATED_USER not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("CREATED_USER between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("CREATED_USER not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNull() {
            addCriterion("MODIFIED_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNotNull() {
            addCriterion("MODIFIED_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserEqualTo(String value) {
            addCriterion("MODIFIED_USER =", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotEqualTo(String value) {
            addCriterion("MODIFIED_USER <>", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThan(String value) {
            addCriterion("MODIFIED_USER >", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIED_USER >=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThan(String value) {
            addCriterion("MODIFIED_USER <", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFIED_USER <=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLike(String value) {
            addCriterion("MODIFIED_USER like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotLike(String value) {
            addCriterion("MODIFIED_USER not like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIn(List<String> values) {
            addCriterion("MODIFIED_USER in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotIn(List<String> values) {
            addCriterion("MODIFIED_USER not in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserBetween(String value1, String value2) {
            addCriterion("MODIFIED_USER between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotBetween(String value1, String value2) {
            addCriterion("MODIFIED_USER not between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1IsNull() {
            addCriterion("STAND_BY_FLAG1 is null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1IsNotNull() {
            addCriterion("STAND_BY_FLAG1 is not null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1EqualTo(String value) {
            addCriterion("STAND_BY_FLAG1 =", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1NotEqualTo(String value) {
            addCriterion("STAND_BY_FLAG1 <>", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1GreaterThan(String value) {
            addCriterion("STAND_BY_FLAG1 >", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1GreaterThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG1 >=", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1LessThan(String value) {
            addCriterion("STAND_BY_FLAG1 <", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1LessThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG1 <=", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1Like(String value) {
            addCriterion("STAND_BY_FLAG1 like", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1NotLike(String value) {
            addCriterion("STAND_BY_FLAG1 not like", value, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1In(List<String> values) {
            addCriterion("STAND_BY_FLAG1 in", values, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1NotIn(List<String> values) {
            addCriterion("STAND_BY_FLAG1 not in", values, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1Between(String value1, String value2) {
            addCriterion("STAND_BY_FLAG1 between", value1, value2, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag1NotBetween(String value1, String value2) {
            addCriterion("STAND_BY_FLAG1 not between", value1, value2, "standByFlag1");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2IsNull() {
            addCriterion("STAND_BY_FLAG2 is null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2IsNotNull() {
            addCriterion("STAND_BY_FLAG2 is not null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2EqualTo(String value) {
            addCriterion("STAND_BY_FLAG2 =", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2NotEqualTo(String value) {
            addCriterion("STAND_BY_FLAG2 <>", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2GreaterThan(String value) {
            addCriterion("STAND_BY_FLAG2 >", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2GreaterThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG2 >=", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2LessThan(String value) {
            addCriterion("STAND_BY_FLAG2 <", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2LessThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG2 <=", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2Like(String value) {
            addCriterion("STAND_BY_FLAG2 like", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2NotLike(String value) {
            addCriterion("STAND_BY_FLAG2 not like", value, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2In(List<String> values) {
            addCriterion("STAND_BY_FLAG2 in", values, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2NotIn(List<String> values) {
            addCriterion("STAND_BY_FLAG2 not in", values, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2Between(String value1, String value2) {
            addCriterion("STAND_BY_FLAG2 between", value1, value2, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag2NotBetween(String value1, String value2) {
            addCriterion("STAND_BY_FLAG2 not between", value1, value2, "standByFlag2");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3IsNull() {
            addCriterion("STAND_BY_FLAG3 is null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3IsNotNull() {
            addCriterion("STAND_BY_FLAG3 is not null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3EqualTo(String value) {
            addCriterion("STAND_BY_FLAG3 =", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3NotEqualTo(String value) {
            addCriterion("STAND_BY_FLAG3 <>", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3GreaterThan(String value) {
            addCriterion("STAND_BY_FLAG3 >", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3GreaterThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG3 >=", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3LessThan(String value) {
            addCriterion("STAND_BY_FLAG3 <", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3LessThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG3 <=", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3Like(String value) {
            addCriterion("STAND_BY_FLAG3 like", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3NotLike(String value) {
            addCriterion("STAND_BY_FLAG3 not like", value, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3In(List<String> values) {
            addCriterion("STAND_BY_FLAG3 in", values, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3NotIn(List<String> values) {
            addCriterion("STAND_BY_FLAG3 not in", values, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3Between(String value1, String value2) {
            addCriterion("STAND_BY_FLAG3 between", value1, value2, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag3NotBetween(String value1, String value2) {
            addCriterion("STAND_BY_FLAG3 not between", value1, value2, "standByFlag3");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4IsNull() {
            addCriterion("STAND_BY_FLAG4 is null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4IsNotNull() {
            addCriterion("STAND_BY_FLAG4 is not null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4EqualTo(String value) {
            addCriterion("STAND_BY_FLAG4 =", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4NotEqualTo(String value) {
            addCriterion("STAND_BY_FLAG4 <>", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4GreaterThan(String value) {
            addCriterion("STAND_BY_FLAG4 >", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4GreaterThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG4 >=", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4LessThan(String value) {
            addCriterion("STAND_BY_FLAG4 <", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4LessThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG4 <=", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4Like(String value) {
            addCriterion("STAND_BY_FLAG4 like", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4NotLike(String value) {
            addCriterion("STAND_BY_FLAG4 not like", value, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4In(List<String> values) {
            addCriterion("STAND_BY_FLAG4 in", values, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4NotIn(List<String> values) {
            addCriterion("STAND_BY_FLAG4 not in", values, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4Between(String value1, String value2) {
            addCriterion("STAND_BY_FLAG4 between", value1, value2, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag4NotBetween(String value1, String value2) {
            addCriterion("STAND_BY_FLAG4 not between", value1, value2, "standByFlag4");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5IsNull() {
            addCriterion("STAND_BY_FLAG5 is null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5IsNotNull() {
            addCriterion("STAND_BY_FLAG5 is not null");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5EqualTo(String value) {
            addCriterion("STAND_BY_FLAG5 =", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5NotEqualTo(String value) {
            addCriterion("STAND_BY_FLAG5 <>", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5GreaterThan(String value) {
            addCriterion("STAND_BY_FLAG5 >", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5GreaterThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG5 >=", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5LessThan(String value) {
            addCriterion("STAND_BY_FLAG5 <", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5LessThanOrEqualTo(String value) {
            addCriterion("STAND_BY_FLAG5 <=", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5Like(String value) {
            addCriterion("STAND_BY_FLAG5 like", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5NotLike(String value) {
            addCriterion("STAND_BY_FLAG5 not like", value, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5In(List<String> values) {
            addCriterion("STAND_BY_FLAG5 in", values, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5NotIn(List<String> values) {
            addCriterion("STAND_BY_FLAG5 not in", values, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5Between(String value1, String value2) {
            addCriterion("STAND_BY_FLAG5 between", value1, value2, "standByFlag5");
            return (Criteria) this;
        }

        public Criteria andStandByFlag5NotBetween(String value1, String value2) {
            addCriterion("STAND_BY_FLAG5 not between", value1, value2, "standByFlag5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_code
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dic_code
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}