pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  datasource:
    druid:
      url: jdbc:mysql://114.115.152.43/xiaofengzi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: '!lichao0810'
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
      connectionInitSqls: set names utf8mb4
  #redis配置
  redis.:
    host:  114.115.152.43
    database:  0
    port:  8081
    password: lichao0810
    #连接池配置
    jedis:
      pool.:
        max-idle:  8
        min-idle:  0
        max-active:  8
        max-wait:  1
logging:
  config: classpath:log4j2-dev.yml
xiaofengzi:
  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: local
    # 本地对象存储配置信息
    local:
      storagePath: /opt/storage
      # 这个地方应该是wx模块的StorageController的fetch方法对应的地址
      address: http://www.xiaofengzi.top/xiaofengzi/api/xfz/storage/fetch
    # 阿里云对象存储配置信息
