spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8088
  servlet:
    context-path: /xiaofengzi

mybatis:
  mapper-locations:
  - classpath:mybatis/**/*.xml
  base-package: com.xiaofengzi.xfzzone.db.dao.generated.mapper
  config-location:

